import { ANALYTICS_EVENTS } from "@/lib/analytics/events";
import { trackServer } from "@/lib/analytics/server";
import { getSession } from "@/lib/auth/get-session";
import { getUserPlanSnapshot } from "@/lib/data/queries/plan";
import { type ICSEvent, buildICS, termToStartDate } from "@/lib/exports/ics";
import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

export async function GET(): Promise<Response> {
  const session = await getSession();
  if (!session) return NextResponse.json({ error: "Not authenticated" }, { status: 401 });

  const { userPlan, catalog } = await getUserPlanSnapshot(session.user.id);

  const events: ICSEvent[] = [];
  for (const p of userPlan) {
    if (p.status === "dropped" || p.status === "disc" || p.status === "failed") continue;
    const date = termToStartDate(p.term);
    if (!date) continue;
    const course = catalog.get(p.courseCode);
    events.push({
      uid: `${p.courseCode.replace(/\s+/g, "-")}-${p.term.replace(/\s+/g, "-")}`,
      summary: `${p.courseCode} — ${course?.title ?? "Course"}`,
      description: `${course?.credits ?? "?"} credits · ${p.status}. Generated by SOEN Compass.`,
      date,
    });
  }

  const ics = buildICS("SOEN Compass Plan", events);

  void trackServer(session.user.id, ANALYTICS_EVENTS.export_ics);

  return new Response(ics, {
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": 'attachment; filename="soen-compass-plan.ics"',
      "Cache-Control": "no-store",
    },
  });
}
